# Site settings
title: Floodgate Academy
email: hello@floodgateacademy.com
description: > # this means to ignore newlines until "baseurl:"
  Floodgate Academy is a training program designed to solve the lack of diversity in the technology industry by creating a pipeline of technically proficient developer operations engineers from underrepresented communities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://floodgateacademy.com" # the base hostname & protocol for your site
twitter_username: wearefgacademy
github_username:  floodgateacademy

# Build settings
markdown: kramdown
